name: Learn actions workflow
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4.2.2
            - name: Using script
              run: bash script.sh