name: sample workflow
on: [push, fork]

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome message
              run: echo "My first Github action Job... Yaay"
            - name: list files
              run: ls
            - name: read files
              run: cat get_secrets.py